name: registration
description: register a this1 identifier
title: "registration"
labels: ["registration"]
body:
  - type: input
    id: identifier
    attributes:
      label: what identifier are you registering?
      description: it must be numeric and not yet taken (check [the list](https://purl.archive.org/this1))
    validations:
      required: true
