name: register

on: issues

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - id: process
        run: printf 'the identifier %s is already taken\n' ${{ toJSON(steps.parse.outputs.data) }}
      - uses: peter-evans/close-issue@v3.0.1
        with:
          comment: ${{steps.process.outputs.comment}}
